# Generated by Django 2.2.6 on 2020-01-02 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191223_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datePublished',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
